/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Main.User.Component;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Asus
 */
public class CardPlayer extends javax.swing.JPanel {

    /**s
     * Creates new form CardPlayer
     */
    public CardPlayer(String kodeNews, String judulNews, String deskripsiNews, String kategoriNews,String fileImage) {
        initComponents();
        LabelIdNews.setText(kodeNews);
        LabelImage1.setText(fileImage);
        LblJudul.setText(judulNews);
        LblDeskripsi.setText(deskripsiNews);
        Lblkategori.setText(kategoriNews);
        
        String ImageNews = LabelImage1.getText().toString();
        
        ImageIcon imageIcon = new ImageIcon(ImageNews);
        
        int labelWidth = 518;
                int labelHeight = 197;

        int imageWidth = imageIcon.getIconWidth();
        int imageHeight = imageIcon.getIconHeight();

        double scaleX = (double) labelWidth / (double) imageWidth;
        double scaleY = (double) labelHeight / (double) imageHeight;
        double scale = Math.min(scaleX, scaleY);

        Image ScaleImage = imageIcon.getImage().getScaledInstance((int) (scale * imageWidth), (int) (scale * imageHeight), Image.SCALE_SMOOTH);

        ImageBerita.setIcon(new ImageIcon(ScaleImage));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageBerita = new javax.swing.JLabel();
        LabelIdNews = new javax.swing.JLabel();
        LabelImage1 = new javax.swing.JLabel();
        LblJudul = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Lblkategori = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LblDeskripsi = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ImageBerita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/DashboardUser/ImageNews.png"))); // NOI18N
        add(ImageBerita, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 418, 177));

        LabelIdNews.setText("Label Id");
        add(LabelIdNews, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 420, -1));

        LabelImage1.setText("Label Image");
        add(LabelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, -1));

        LblJudul.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        LblJudul.setText("jLabel1");
        add(LblJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 420, 60));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/DashboardUser/Icon/IconNews.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 60, 50));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 3, 30));

        Lblkategori.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        Lblkategori.setText("Contoh Saja Ya");
        add(Lblkategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 350, 50));

        LblDeskripsi.setColumns(20);
        LblDeskripsi.setRows(5);
        LblDeskripsi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        jScrollPane1.setViewportView(LblDeskripsi);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 420, 100));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImageBerita;
    private javax.swing.JLabel LabelIdNews;
    private javax.swing.JLabel LabelImage1;
    private javax.swing.JTextArea LblDeskripsi;
    private javax.swing.JLabel LblJudul;
    private javax.swing.JLabel Lblkategori;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
