/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Main.User.Component;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Asus
 */
public class CardPlayers extends javax.swing.JPanel {

    /**
     * Creates new form CardPlayers
     */
    public CardPlayers(String idPlayer, String firstName, String LastName, String positionPlayer
            ,String numberPlayer,String imagePlayer) {
        
        initComponents();
        
        Lblimage.setVisible(false);
        Lblid.setText(idPlayer);
        Lblfirst.setText(firstName);
        Lbllast.setText(LastName);
        Lblposition.setText(positionPlayer);
        Lblnumber.setText(numberPlayer);
        Lblimage.setText(imagePlayer);
        LoadImage();
        
    }
    
    private void LoadImage(){
        String ImagePlayer = Lblimage.getText().toString();
        
        ImageIcon imageIcon = new ImageIcon(ImagePlayer);
        
        int labelWidth = 350;
        int labelHeight = 290;

        int imageWidth = imageIcon.getIconWidth();
        int imageHeight = imageIcon.getIconHeight();

        double scaleX = (double) labelWidth / (double) imageWidth;
        double scaleY = (double) labelHeight / (double) imageHeight;
        double scale = Math.min(scaleX, scaleY);

        Image ScaleImage = imageIcon.getImage().getScaledInstance((int) (scale * imageWidth), (int) (scale * imageHeight), Image.SCALE_SMOOTH);

        ImagePlayers.setIcon(new ImageIcon(ScaleImage));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lblposition = new javax.swing.JLabel();
        ImagePlayers = new javax.swing.JLabel();
        Lblfirst = new javax.swing.JLabel();
        Lbllast = new javax.swing.JLabel();
        Lblimage = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Lblid = new javax.swing.JLabel();
        Lblnumber = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(310, 343));
        setPreferredSize(new java.awt.Dimension(310, 343));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lblposition.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        Lblposition.setText("GoalKeeper");
        add(Lblposition, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 260, 50));

        ImagePlayers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/DashboardUser/Andre Onana.png"))); // NOI18N
        ImagePlayers.setMaximumSize(new java.awt.Dimension(310, 290));
        ImagePlayers.setMinimumSize(new java.awt.Dimension(310, 290));
        add(ImagePlayers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, -1));

        Lblfirst.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        Lblfirst.setText("Andre");
        add(Lblfirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 306, 309, 20));

        Lbllast.setFont(new java.awt.Font("Verdana", 1, 40)); // NOI18N
        Lbllast.setText("Onana");
        add(Lbllast, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 328, 309, 40));

        Lblimage.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        Lblimage.setText("GoalKeeper");
        add(Lblimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 310, 50));

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 2, 30));

        Lblid.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        Lblid.setText("GoalKeeper");
        add(Lblid, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 310, 50));

        Lblnumber.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        Lblnumber.setText("90");
        add(Lblnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 30, 50));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 320, 50));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImagePlayers;
    private javax.swing.JLabel Lblfirst;
    private javax.swing.JLabel Lblid;
    private javax.swing.JLabel Lblimage;
    private javax.swing.JLabel Lbllast;
    private javax.swing.JLabel Lblnumber;
    private javax.swing.JLabel Lblposition;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
