/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Main.User.Component;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Asus
 */
public class CardNews extends javax.swing.JPanel {

    /**
     * s
     * Creates new form CardPlayer
     */
    public CardNews(String kodeNews, String judulNews, String deskripsiNews, String kategoriNews, String fileImage) {
        initComponents();
        LabelIdNews.setText(kodeNews);
        LabelImage1.setText(fileImage);
        LblJudul.setText(judulNews);
        LblDeskripsi.setText(deskripsiNews);
        Lblkategori.setText(kategoriNews);

        Line.setVisible(false);
        LoadDataCard();

        LabelImage1.setVisible(false);
    }

    private void LoadDataCard() {
        String ImageNews = LabelImage1.getText().toString();

        ImageIcon imageIcon = new ImageIcon(ImageNews);

        int labelWidth = 413;
        int labelHeight = 185;

        int imageWidth = imageIcon.getIconWidth();
        int imageHeight = imageIcon.getIconHeight();

        double scaleX = (double) labelWidth / (double) imageWidth;
        double scaleY = (double) labelHeight / (double) imageHeight;
        double scale = Math.min(scaleX, scaleY);

        Image ScaleImage = imageIcon.getImage().getScaledInstance((int) (scale * imageWidth), (int) (scale * imageHeight), Image.SCALE_SMOOTH);

        ImageBerita.setIcon(new ImageIcon(ScaleImage));

        LblDeskripsi.setLineWrap(true);
        LblDeskripsi.setWrapStyleWord(true); // Memaksa pemisahan kata hanya terjadi pada batas kata
        LblDeskripsi.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Line = new javax.swing.JPanel();
        ImageBerita = new javax.swing.JLabel();
        LabelIdNews = new javax.swing.JLabel();
        LabelImage1 = new javax.swing.JLabel();
        LblJudul = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Lblkategori = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LblDeskripsi = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Line.setBackground(new java.awt.Color(240, 0, 0));

        javax.swing.GroupLayout LineLayout = new javax.swing.GroupLayout(Line);
        Line.setLayout(LineLayout);
        LineLayout.setHorizontalGroup(
            LineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 135, Short.MAX_VALUE)
        );
        LineLayout.setVerticalGroup(
            LineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        add(Line, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 185, 135, 3));

        ImageBerita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/DashboardUser/ImageNews.png"))); // NOI18N
        add(ImageBerita, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 418, 177));

        LabelIdNews.setText("Label Id");
        add(LabelIdNews, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 420, -1));

        LabelImage1.setText("Label Image");
        add(LabelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, -1));

        LblJudul.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        LblJudul.setForeground(new java.awt.Color(204, 0, 0));
        LblJudul.setText("jLabel1");
        LblJudul.setAlignmentX(0.5F);
        LblJudul.setIconTextGap(10);
        add(LblJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 410, 60));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/DashboardUser/Icon/IconNews.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 60, 50));

        Lblkategori.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        Lblkategori.setText("Contoh Saja Ya");
        add(Lblkategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 350, 50));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 3, 30));

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(420, 53));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 420, 53));

        LblDeskripsi.setColumns(20);
        LblDeskripsi.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        LblDeskripsi.setRows(5);
        LblDeskripsi.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.white));
        LblDeskripsi.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        LblDeskripsi.setEnabled(false);
        LblDeskripsi.setFocusable(false);
        LblDeskripsi.setMargin(new java.awt.Insets(2, 15, 2, 10));
        jScrollPane1.setViewportView(LblDeskripsi);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 420, 100));
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
        Line.setVisible(true);
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        // TODO add your handling code here:
        Line.setVisible(false);
    }//GEN-LAST:event_formMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImageBerita;
    private javax.swing.JLabel LabelIdNews;
    private javax.swing.JLabel LabelImage1;
    private javax.swing.JTextArea LblDeskripsi;
    private javax.swing.JLabel LblJudul;
    private javax.swing.JLabel Lblkategori;
    private javax.swing.JPanel Line;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
