/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Menu;

import Koneksi.Config;
import Main.LoginForm;
import java.awt.HeadlessException;
import java.awt.Color;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author Asus
 */
public class RegisterPage extends javax.swing.JPanel {

    /**
     * Creates new form RegisterPage
     */
    public RegisterPage() {
        initComponents();
        
        txtpassword.setText("Input password");
        txtpassword.setEchoChar((char) 0);
        
        txtconfirm.setText("Confirm password");
        txtconfirm.setEchoChar((char) 0);
    }
    
    private void RegisterQuery(){
        String role = "User";
        int id=2;
        try{
            String sql = "INSERT INTO user VALUES ('"+id+"','"+txtname.getText()+"','"+txtemail.getText()+"','"+txtpassword.getText()+"','"+txttelepon.getText()+"','"+role+ "')";
            java.sql.Connection conn = (Connection)Config.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Register Succesfully.");
            
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegisterPanel = new javax.swing.JPanel();
        lbljudul = new javax.swing.JLabel();
        lbldeskripsi = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        lblemail = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        lblpassword = new javax.swing.JLabel();
        lblconfirm = new javax.swing.JLabel();
        lbltelepon = new javax.swing.JLabel();
        txttelepon = new javax.swing.JTextField();
        btnregister = new rojerusan.RSMaterialButtonRectangle();
        lbllink = new javax.swing.JLabel();
        linklogin = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        txtconfirm = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(255, 255, 255));

        RegisterPanel.setBackground(new java.awt.Color(255, 255, 255));
        RegisterPanel.setPreferredSize(new java.awt.Dimension(561, 818));

        lbljudul.setFont(new java.awt.Font("Verdana", 1, 60)); // NOI18N
        lbljudul.setText("REGISTER");

        lbldeskripsi.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lbldeskripsi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldeskripsi.setText("Register now to unclock your exclusive access to contents.");

        lblname.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblname.setText("Name");

        txtname.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtname.setForeground(new java.awt.Color(204, 204, 204));
        txtname.setText("Input name");
        txtname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtname.setCaretColor(new java.awt.Color(93, 95, 239));
        txtname.setDisabledTextColor(new java.awt.Color(93, 95, 239));
        txtname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnameFocusLost(evt);
            }
        });

        lblemail.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblemail.setText("Email address");

        txtemail.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtemail.setForeground(new java.awt.Color(204, 204, 204));
        txtemail.setText("Input email");
        txtemail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtemail.setCaretColor(new java.awt.Color(93, 95, 239));
        txtemail.setDisabledTextColor(new java.awt.Color(93, 95, 239));
        txtemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtemailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtemailFocusLost(evt);
            }
        });
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });

        lblpassword.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblpassword.setText("Password");

        lblconfirm.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblconfirm.setText("Confirm Password");

        lbltelepon.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lbltelepon.setText("No Telepon");

        txttelepon.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txttelepon.setForeground(new java.awt.Color(204, 204, 204));
        txttelepon.setText("Input telepon");
        txttelepon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txttelepon.setCaretColor(new java.awt.Color(93, 95, 239));
        txttelepon.setDisabledTextColor(new java.awt.Color(93, 95, 239));
        txttelepon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtteleponFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtteleponFocusLost(evt);
            }
        });
        txttelepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtteleponActionPerformed(evt);
            }
        });

        btnregister.setBackground(new java.awt.Color(204, 0, 0));
        btnregister.setText("REGISTER");
        btnregister.setBorderPainted(false);
        btnregister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnregister.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        btnregister.setRippleColor(new java.awt.Color(0, 255, 204));
        btnregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregisterActionPerformed(evt);
            }
        });

        lbllink.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        lbllink.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllink.setText("Do you have an Account?");

        linklogin.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        linklogin.setForeground(new java.awt.Color(204, 0, 0));
        linklogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        linklogin.setText("Login here");
        linklogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linklogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkloginMouseClicked(evt);
            }
        });

        txtpassword.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtpassword.setForeground(new java.awt.Color(204, 204, 204));
        txtpassword.setText("Input password");
        txtpassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpasswordFocusLost(evt);
            }
        });

        txtconfirm.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtconfirm.setForeground(new java.awt.Color(204, 204, 204));
        txtconfirm.setText("Confirm password");
        txtconfirm.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtconfirm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtconfirmFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtconfirmFocusLost(evt);
            }
        });

        javax.swing.GroupLayout RegisterPanelLayout = new javax.swing.GroupLayout(RegisterPanel);
        RegisterPanel.setLayout(RegisterPanelLayout);
        RegisterPanelLayout.setHorizontalGroup(
            RegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lbldeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 43, Short.MAX_VALUE))
            .addGroup(RegisterPanelLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(lbljudul)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(RegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblconfirm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbltelepon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblemail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblpassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txttelepon, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtconfirm, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtpassword, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtemail, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtname, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnregister, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterPanelLayout.createSequentialGroup()
                        .addComponent(lbllink)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(linklogin, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)))
                .addGap(53, 53, 53))
        );
        RegisterPanelLayout.setVerticalGroup(
            RegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbljudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbldeskripsi)
                .addGap(34, 34, 34)
                .addComponent(lblname)
                .addGap(10, 10, 10)
                .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(lblemail)
                .addGap(10, 10, 10)
                .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(lblpassword)
                .addGap(10, 10, 10)
                .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(lblconfirm)
                .addGap(15, 15, 15)
                .addComponent(txtconfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(lbltelepon)
                .addGap(10, 10, 10)
                .addComponent(txttelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnregister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(RegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbllink)
                    .addComponent(linklogin))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(RegisterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(RegisterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txtteleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtteleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtteleponActionPerformed

    private void linkloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkloginMouseClicked
        // TODO add your handling code here:
        LoginForm container = new LoginForm();

        javax.swing.JPanel loginPanel = container.getLoginPanel();
        
        this.removeAll();       
        this.repaint();
        this.revalidate();
        this.add(loginPanel);
        this.repaint();
        this.revalidate();
      
    }//GEN-LAST:event_linkloginMouseClicked

    private void btnregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregisterActionPerformed
        // TODO add your handling code here:;
        RegisterQuery();
    }//GEN-LAST:event_btnregisterActionPerformed

    private void txtpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpasswordFocusGained
        // TODO add your handling code here:
        if(txtpassword.getText().equals("Input password")){
            txtpassword.setText("");
            txtpassword.setEchoChar('*');
            txtpassword.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtpasswordFocusGained

    private void txtpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpasswordFocusLost
        // TODO add your handling code here:
        if(txtpassword.getText().equals("")){
            txtpassword.setText("Input password");
            txtpassword.setEchoChar((char) 0);
            txtpassword.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txtpasswordFocusLost

    private void txtconfirmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtconfirmFocusGained
        // TODO add your handling code here:
        if(txtconfirm.getText().equals("Confirm password")){
            txtconfirm.setText("");
            txtconfirm.setEchoChar('*');
            txtconfirm.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtconfirmFocusGained

    private void txtconfirmFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtconfirmFocusLost
        // TODO add your handling code here:
        if(txtconfirm.getText().equals("")){
            txtconfirm.setText("Confirm password");
            txtconfirm.setEchoChar((char) 0);
            txtconfirm.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txtconfirmFocusLost

    private void txtnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnameFocusGained
        // TODO add your handling code here:
        if(txtname.getText().equals("Input name")){
            txtname.setText("");
            txtname.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtnameFocusGained

    private void txtnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnameFocusLost
        // TODO add your handling code here:
        if(txtname.getText().equals("")){
            txtname.setText("Input name");
            txtname.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txtnameFocusLost

    private void txtemailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtemailFocusGained
        // TODO add your handling code here:
        if(txtemail.getText().equals("Input email")){
            txtemail.setText("");
            txtemail.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtemailFocusGained

    private void txtteleponFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtteleponFocusGained
        // TODO add your handling code here:
        if(txttelepon.getText().equals("Input telepon")){
            txttelepon.setText("");
            txttelepon.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtteleponFocusGained

    private void txtteleponFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtteleponFocusLost
        // TODO add your handling code here:
        if(txttelepon.getText().equals("")){
            txttelepon.setText("Input telepon");
            txttelepon.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txtteleponFocusLost

    private void txtemailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtemailFocusLost
        // TODO add your handling code here:
        if(txtemail.getText().equals("")){
            txtemail.setText("Input email");
            txtemail.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txtemailFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel RegisterPanel;
    public rojerusan.RSMaterialButtonRectangle btnregister;
    public javax.swing.JLabel lblconfirm;
    public javax.swing.JLabel lbldeskripsi;
    public javax.swing.JLabel lblemail;
    public javax.swing.JLabel lbljudul;
    public javax.swing.JLabel lbllink;
    public javax.swing.JLabel lblname;
    public javax.swing.JLabel lblpassword;
    public javax.swing.JLabel lbltelepon;
    public javax.swing.JLabel linklogin;
    public javax.swing.JPasswordField txtconfirm;
    public javax.swing.JTextField txtemail;
    public javax.swing.JTextField txtname;
    public javax.swing.JPasswordField txtpassword;
    public javax.swing.JTextField txttelepon;
    // End of variables declaration//GEN-END:variables
}
