/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Menu;

/**
 *
 * @author Asus
 */
public class UserPage extends javax.swing.JPanel {

    /**
     * Creates new form NotFoundForm
     */
    public UserPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableUser = new javax.swing.JTable();
        rSMaterialButtonRectangle2 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle6 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle7 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle8 = new rojerusan.RSMaterialButtonRectangle();
        jTextField1 = new javax.swing.JTextField();
        rSMaterialButtonRectangle3 = new rojerusan.RSMaterialButtonRectangle();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(240, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 290, 5));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 25)); // NOI18N
        jLabel1.setText("MANAGE DATA USER");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 290, 30));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel2.setText("Kode User");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 120, -1));

        jTextField2.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jTextField2.setText("jTextField2");
        jTextField2.setMargin(new java.awt.Insets(2, 10, 2, 10));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 420, 50));

        jTextField3.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jTextField3.setText("jTextField2");
        jTextField3.setMargin(new java.awt.Insets(2, 10, 2, 10));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 420, 50));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel3.setText("Kode User");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 120, -1));

        jTextField4.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jTextField4.setText("jTextField2");
        jTextField4.setMargin(new java.awt.Insets(2, 10, 2, 10));
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 420, 50));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel4.setText("Kode User");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 120, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel5.setText("Kode User");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 120, -1));

        jTextField5.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jTextField5.setText("jTextField2");
        jTextField5.setMargin(new java.awt.Insets(2, 10, 2, 10));
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 430, 50));

        jTextField6.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jTextField6.setText("jTextField2");
        jTextField6.setMargin(new java.awt.Insets(2, 10, 2, 10));
        add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 430, 50));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel6.setText("Kode User");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 120, -1));

        jTextField7.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jTextField7.setText("jTextField2");
        jTextField7.setMargin(new java.awt.Insets(2, 10, 2, 10));
        add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, 430, 50));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel7.setText("Kode User");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 120, -1));

        TableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TableUser);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 1110, 310));

        rSMaterialButtonRectangle2.setText("CANCEL");
        rSMaterialButtonRectangle2.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        add(rSMaterialButtonRectangle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 540, 220, 60));

        rSMaterialButtonRectangle6.setText("CREATE");
        rSMaterialButtonRectangle6.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        add(rSMaterialButtonRectangle6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 230, 60));

        rSMaterialButtonRectangle7.setText("UPDATE");
        rSMaterialButtonRectangle7.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        add(rSMaterialButtonRectangle7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 220, 60));

        rSMaterialButtonRectangle8.setText("DELETE");
        rSMaterialButtonRectangle8.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        add(rSMaterialButtonRectangle8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, 220, 60));

        jTextField1.setText("jTextField1");
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, 660, 50));

        rSMaterialButtonRectangle3.setText("CANCEL");
        rSMaterialButtonRectangle3.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        add(rSMaterialButtonRectangle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 450, 220, 60));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle2;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle3;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle6;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle7;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle8;
    // End of variables declaration//GEN-END:variables
}
