/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Menu;

import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class UserPage extends javax.swing.JPanel {

    /**
     * Creates new form NotFoundForm
     */
    public UserPage() {
        initComponents();
        
        LockInputan();
        ButtonEnabled();
    }
    
    private void LockInputan(){
        txtkode.setEnabled(false);
        txtname.setEnabled(false);
        txtemail.setEnabled(false);
        txtpassword.setEnabled(false);
        txttelepon.setEnabled(false);
        txtrole.setEnabled(false);
    }
    
    private void OpenInputan(){
        txtkode.setEnabled(true);
        txtname.setEnabled(true);
        txtemail.setEnabled(true);
        txtpassword.setEnabled(true);
        txttelepon.setEnabled(true);
        txtrole.setEnabled(true);
    }
    
    private void ClearForm(){
        txtkode.setEditable(true);
        txtname.setText(null);
        txtemail.setText(null);
        txtpassword.setText(null);
        txtrole.setSelectedIndex(0);
        txttelepon.setText(null);
    }
    
    
    private void ButtonEnabled(){
        BCreate.setEnabled(true);
        BUpdate.setEnabled(true);
        BDelete.setEnabled(true);
        BCancel.setEnabled(true);
    }
    
    // bagian CRUD
    
    private void ShowTable(){
        
    }
     
    private void CreateQuery(){
        
    }
    
    private void UpdateQuery(){
        
    }
    
    private void DeleteQuery(){
        
    }
    
    // selesai bagian CRUD

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtkode = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JTextField();
        txttelepon = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableUser = new javax.swing.JTable();
        BSearch = new rojerusan.RSMaterialButtonRectangle();
        BCreate = new rojerusan.RSMaterialButtonRectangle();
        BUpdate = new rojerusan.RSMaterialButtonRectangle();
        BDelete = new rojerusan.RSMaterialButtonRectangle();
        BCancel = new rojerusan.RSMaterialButtonRectangle();
        txtrole = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(240, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 290, 5));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 25)); // NOI18N
        jLabel1.setText("MANAGE DATA USER");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 290, 30));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel2.setText("Kode user");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 120, -1));

        txtkode.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtkode.setMargin(new java.awt.Insets(2, 10, 2, 10));
        txtkode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkodeActionPerformed(evt);
            }
        });
        add(txtkode, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 480, 50));

        txtname.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtname.setMargin(new java.awt.Insets(2, 10, 2, 10));
        add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 480, 50));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel3.setText("Name user");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 120, -1));

        txtemail.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtemail.setMargin(new java.awt.Insets(2, 10, 2, 10));
        add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 480, 50));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel4.setText("Email address");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 130, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel5.setText("Password user");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 130, -1));

        txtpassword.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtpassword.setMargin(new java.awt.Insets(2, 10, 2, 10));
        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });
        add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 520, 50));

        txttelepon.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txttelepon.setMargin(new java.awt.Insets(2, 10, 2, 10));
        add(txttelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 520, 50));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel6.setText("Nomor telepon");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 140, -1));

        txtsearch.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtsearch.setText("jTextField2");
        txtsearch.setMargin(new java.awt.Insets(2, 10, 2, 10));
        add(txtsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 790, 50));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel7.setText("Role user");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 120, -1));

        TableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TableUser);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 1110, 310));

        BSearch.setBackground(new java.awt.Color(204, 204, 204));
        BSearch.setForeground(new java.awt.Color(0, 0, 0));
        BSearch.setText("SEARCH");
        BSearch.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        BSearch.setType(rojerusan.RSMaterialButtonRectangle.Type.RAISED);
        add(BSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 540, 220, 50));

        BCreate.setBackground(new java.awt.Color(0, 153, 0));
        BCreate.setText("CREATE");
        BCreate.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        BCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCreateActionPerformed(evt);
            }
        });
        add(BCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 240, 60));

        BUpdate.setBackground(new java.awt.Color(255, 153, 0));
        BUpdate.setText("UPDATE");
        BUpdate.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        BUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUpdateActionPerformed(evt);
            }
        });
        add(BUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 250, 60));

        BDelete.setBackground(new java.awt.Color(204, 0, 0));
        BDelete.setText("DELETE");
        BDelete.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        BDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDeleteActionPerformed(evt);
            }
        });
        add(BDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 450, 250, 60));

        BCancel.setBackground(new java.awt.Color(51, 51, 255));
        BCancel.setText("CANCEL");
        BCancel.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        BCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCancelActionPerformed(evt);
            }
        });
        add(BCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 450, 240, 60));

        txtrole.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtrole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        txtrole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtroleActionPerformed(evt);
            }
        });
        add(txtrole, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 520, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordActionPerformed

    private void txtroleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtroleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtroleActionPerformed

    private void txtkodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkodeActionPerformed

    private void BCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCreateActionPerformed
        // TODO add your handling code here:
         if (BCreate.getText().equals("CREATE")) {
            BCreate.setText("SUBMIT");
            BUpdate.setEnabled(false);
            BDelete.setEnabled(false);
            BCancel.setText("CANCEL");

            OpenInputan();
        } else if (BCreate.getText().equals("SUBMIT")) {
            if (txtkode.getText().equals("") || txtname.getText().equals("")
                    || txtemail.getText().equals("") || txtpassword.getText().equals("")
                    || txttelepon.getText().equals("")
                    || txtrole.getSelectedItem().equals("")) {
                JOptionPane.showMessageDialog(null, "Please Input All Inputan");
                txtkode.requestFocus();
            } else {
                BCreate.setText("CREATE");
            }
        }
    }//GEN-LAST:event_BCreateActionPerformed

    private void BUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUpdateActionPerformed
        // TODO add your handling code here:
        if (BUpdate.getText().equals("UPDATE")) {
            BUpdate.setText("SUBMIT");
            BCreate.setEnabled(false);
            BDelete.setEnabled(false);
            BCancel.setText("CANCEL");

            OpenInputan();
        } else if (BUpdate.getText().equals("SUBMIT")) {
             if (txtkode.getText().equals("") || txtname.getText().equals("")
                    || txtemail.getText().equals("") || txtpassword.getText().equals("")
                    || txttelepon.getText().equals("")
                    || txtrole.getSelectedItem().equals("")) {
                JOptionPane.showMessageDialog(null, "Please Input All Inputan");
                txtkode.requestFocus();
            } else {
                BUpdate.setText("UPDATE");
            }
        }
    }//GEN-LAST:event_BUpdateActionPerformed

    private void BDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDeleteActionPerformed
        // TODO add your handling code here:
        if (BDelete.getText().equals("DELETE")) {
            BDelete.setText("SUBMIT");
            BCreate.setEnabled(false);
            BUpdate.setEnabled(false);
            BCancel.setText("CANCEL");

            OpenInputan();
        } else if (BDelete.getText().equals("SUBMIT")) {
             if (txtkode.getText().equals("") || txtname.getText().equals("")
                    || txtemail.getText().equals("") || txtpassword.getText().equals("")
                    || txttelepon.getText().equals("")
                    || txtrole.getSelectedItem().equals("")) {
                JOptionPane.showMessageDialog(null, "Please Input All Inputan");
                txtkode.requestFocus();
            } else {
                 int inputan = JOptionPane.showConfirmDialog(this,
                        "Apakah Anda yakin delete data tersebut", "Confirm Delete",JOptionPane.YES_NO_OPTION);
                if (inputan == JOptionPane.YES_OPTION){
                    BDelete.setText("DELETE");
                }else{
                    
                }
            }
        }
    }//GEN-LAST:event_BDeleteActionPerformed

    private void BCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCancelActionPerformed
        // TODO add your handling code here:
        if (BCancel.getText().equals("CLEAR")){
            ClearForm();
        }else if (BCancel.getText().equals("CANCEL")){
            ClearForm();
            ButtonEnabled();
            OpenInputan();
            BCancel.setText("CLEAR");
        }
    }//GEN-LAST:event_BCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle BCancel;
    private rojerusan.RSMaterialButtonRectangle BCreate;
    private rojerusan.RSMaterialButtonRectangle BDelete;
    private rojerusan.RSMaterialButtonRectangle BSearch;
    private rojerusan.RSMaterialButtonRectangle BUpdate;
    private javax.swing.JTable TableUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtkode;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JComboBox<String> txtrole;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JTextField txttelepon;
    // End of variables declaration//GEN-END:variables
}
