/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import Menu.NewsPage;
import Menu.UserPage;
import Menu.PlayerPage;
import Menu.StatistikPlayerPage;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.Timer;

/**
 *
 * @author Asus
 */
public class DashboardForm extends javax.swing.JFrame {
    private Timer timer;
    /**
     * Creates new form DashboardForm
     */
    public DashboardForm() {
        initComponents();
        setLocationRelativeTo(null);
        
        MainPanel.removeAll();

        MainPanel.add(PanelDashboard);
        MainPanel.repaint();
        MainPanel.revalidate();
        
        LoadDateTime();
        timer = new Timer(1000, new ActionListener(){
             @Override
             public void actionPerformed(ActionEvent e){
                 LoadDateTime();
             }
        });
        
        timer.start();
    }
    
    private void LoadDateTime(){
        Date now = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String dateTime = dateFormat.format(now);
        LabelDatetime.setText(dateTime);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        ContainerPanel = new javax.swing.JPanel();
        HeaderPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        LabelDatetime = new javax.swing.JLabel();
        SidebarPanel = new javax.swing.JPanel();
        PanelButton = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btndashboard = new javax.swing.JLabel();
        PanelLogout = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnlogout = new javax.swing.JLabel();
        PanelBtnUser = new javax.swing.JPanel();
        btnuser = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        PanelBtnPlayer = new javax.swing.JPanel();
        btnplayer = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        PanelBtnStatistik = new javax.swing.JPanel();
        btnstatistik = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        PanelBtnNews = new javax.swing.JPanel();
        btnnews = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        PanelDashboard = new javax.swing.JPanel();
        PanelImage = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Paneltotal = new javax.swing.JPanel();
        PanelTotalUser = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        LabelUser = new javax.swing.JLabel();
        ValueUser = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        Labeltahunuser = new javax.swing.JLabel();
        PanelTotalPemain = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        LabelPlayer = new javax.swing.JLabel();
        ValuePlayer = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        Labelyear = new javax.swing.JLabel();
        PanelTotalBerita = new javax.swing.JPanel();
        LabelBerita = new javax.swing.JLabel();
        LabelText = new javax.swing.JLabel();
        LabelTotal = new javax.swing.JLabel();
        PanelLine = new javax.swing.JPanel();
        LabelTahun = new javax.swing.JLabel();
        PanelTable = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabledata = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard ManUtd Apps");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/asset/Logo Mu.png")).getImage());
        setResizable(false);

        ContainerPanel.setBackground(new java.awt.Color(255, 255, 255));

        HeaderPanel.setBackground(new java.awt.Color(204, 0, 0));
        HeaderPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Logo MU Shadow.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        HeaderPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 3, 61, 80));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dashboard ManUtd Apps");
        HeaderPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, 45));

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setPreferredSize(new java.awt.Dimension(146, 10));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 59, Short.MAX_VALUE)
        );

        HeaderPanel.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 10, 3, 59));

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("No Room For Racism");
        HeaderPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 10, -1, -1));

        LabelDatetime.setFont(new java.awt.Font("Verdana", 0, 19)); // NOI18N
        LabelDatetime.setForeground(new java.awt.Color(255, 255, 255));
        LabelDatetime.setText("No Room For Racism");
        HeaderPanel.add(LabelDatetime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 40, 235, -1));

        SidebarPanel.setBackground(new java.awt.Color(0, 0, 0));
        SidebarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelButton.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Dashboard/Icon/IconDashboard.png"))); // NOI18N

        btndashboard.setFont(new java.awt.Font("Verdana", 1, 17)); // NOI18N
        btndashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btndashboard.setText("Dashboard");
        btndashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndashboardMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanelButtonLayout = new javax.swing.GroupLayout(PanelButton);
        PanelButton.setLayout(PanelButtonLayout);
        PanelButtonLayout.setHorizontalGroup(
            PanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelButtonLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btndashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
        );
        PanelButtonLayout.setVerticalGroup(
            PanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelButtonLayout.createSequentialGroup()
                .addComponent(btndashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        SidebarPanel.add(PanelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 83, 247, -1));

        PanelLogout.setBackground(new java.awt.Color(240, 0, 0));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Dashboard/Icon/IconNews.png"))); // NOI18N

        btnlogout.setFont(new java.awt.Font("Verdana", 1, 17)); // NOI18N
        btnlogout.setForeground(new java.awt.Color(255, 255, 255));
        btnlogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnlogout.setText("Log Out");
        btnlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnlogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnlogoutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanelLogoutLayout = new javax.swing.GroupLayout(PanelLogout);
        PanelLogout.setLayout(PanelLogoutLayout);
        PanelLogoutLayout.setHorizontalGroup(
            PanelLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelLogoutLayout.setVerticalGroup(
            PanelLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLogoutLayout.createSequentialGroup()
                .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        SidebarPanel.add(PanelLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 850, 275, -1));

        PanelBtnUser.setBackground(new java.awt.Color(255, 255, 255));
        PanelBtnUser.setPreferredSize(new java.awt.Dimension(100, 53));

        btnuser.setFont(new java.awt.Font("Verdana", 1, 17)); // NOI18N
        btnuser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnuser.setText("User");
        btnuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnuserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnuserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnuserMouseExited(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Dashboard/Icon/IconUser.png"))); // NOI18N

        javax.swing.GroupLayout PanelBtnUserLayout = new javax.swing.GroupLayout(PanelBtnUser);
        PanelBtnUser.setLayout(PanelBtnUserLayout);
        PanelBtnUserLayout.setHorizontalGroup(
            PanelBtnUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBtnUserLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnuser, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
        );
        PanelBtnUserLayout.setVerticalGroup(
            PanelBtnUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBtnUserLayout.createSequentialGroup()
                .addComponent(btnuser, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        SidebarPanel.add(PanelBtnUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 156, 247, -1));

        PanelBtnPlayer.setBackground(new java.awt.Color(255, 255, 255));
        PanelBtnPlayer.setPreferredSize(new java.awt.Dimension(100, 53));

        btnplayer.setFont(new java.awt.Font("Verdana", 1, 17)); // NOI18N
        btnplayer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnplayer.setText("Player");
        btnplayer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnplayerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnplayerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnplayerMouseExited(evt);
            }
        });

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Dashboard/Icon/IconPlayer.png"))); // NOI18N

        javax.swing.GroupLayout PanelBtnPlayerLayout = new javax.swing.GroupLayout(PanelBtnPlayer);
        PanelBtnPlayer.setLayout(PanelBtnPlayerLayout);
        PanelBtnPlayerLayout.setHorizontalGroup(
            PanelBtnPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBtnPlayerLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnplayer, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
        );
        PanelBtnPlayerLayout.setVerticalGroup(
            PanelBtnPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBtnPlayerLayout.createSequentialGroup()
                .addComponent(btnplayer, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        SidebarPanel.add(PanelBtnPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 229, 247, -1));

        PanelBtnStatistik.setBackground(new java.awt.Color(255, 255, 255));
        PanelBtnStatistik.setPreferredSize(new java.awt.Dimension(100, 53));

        btnstatistik.setFont(new java.awt.Font("Verdana", 1, 17)); // NOI18N
        btnstatistik.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnstatistik.setText("Statistik Player");
        btnstatistik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnstatistikMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnstatistikMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnstatistikMouseExited(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Dashboard/Icon/IconStatistik.png"))); // NOI18N

        javax.swing.GroupLayout PanelBtnStatistikLayout = new javax.swing.GroupLayout(PanelBtnStatistik);
        PanelBtnStatistik.setLayout(PanelBtnStatistikLayout);
        PanelBtnStatistikLayout.setHorizontalGroup(
            PanelBtnStatistikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBtnStatistikLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnstatistik, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
        );
        PanelBtnStatistikLayout.setVerticalGroup(
            PanelBtnStatistikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBtnStatistikLayout.createSequentialGroup()
                .addComponent(btnstatistik, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        SidebarPanel.add(PanelBtnStatistik, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 302, 247, -1));

        PanelBtnNews.setBackground(new java.awt.Color(255, 255, 255));
        PanelBtnNews.setPreferredSize(new java.awt.Dimension(100, 53));

        btnnews.setFont(new java.awt.Font("Verdana", 1, 17)); // NOI18N
        btnnews.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnnews.setText("News");
        btnnews.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnnewsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnnewsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnnewsMouseExited(evt);
            }
        });

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Dashboard/Icon/IconNews.png"))); // NOI18N

        javax.swing.GroupLayout PanelBtnNewsLayout = new javax.swing.GroupLayout(PanelBtnNews);
        PanelBtnNews.setLayout(PanelBtnNewsLayout);
        PanelBtnNewsLayout.setHorizontalGroup(
            PanelBtnNewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBtnNewsLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnnews, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
        );
        PanelBtnNewsLayout.setVerticalGroup(
            PanelBtnNewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBtnNewsLayout.createSequentialGroup()
                .addComponent(btnnews, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        SidebarPanel.add(PanelBtnNews, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 375, 247, -1));

        MainPanel.setBackground(new java.awt.Color(51, 51, 255));
        MainPanel.setLayout(new java.awt.BorderLayout());

        PanelDashboard.setBackground(new java.awt.Color(255, 255, 255));

        PanelImage.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Dashboard/ImageDashboard.png"))); // NOI18N
        jLabel4.setFocusable(false);

        javax.swing.GroupLayout PanelImageLayout = new javax.swing.GroupLayout(PanelImage);
        PanelImage.setLayout(PanelImageLayout);
        PanelImageLayout.setHorizontalGroup(
            PanelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1104, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        PanelImageLayout.setVerticalGroup(
            PanelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4)
        );

        Paneltotal.setBackground(new java.awt.Color(255, 255, 255));

        PanelTotalUser.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Dashboard/ImagePemain.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
        });

        LabelUser.setFont(new java.awt.Font("Verdana", 1, 25)); // NOI18N
        LabelUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelUser.setText("User Apps");

        ValueUser.setBackground(new java.awt.Color(240, 0, 0));
        ValueUser.setFont(new java.awt.Font("Verdana", 1, 70)); // NOI18N
        ValueUser.setForeground(new java.awt.Color(240, 0, 0));
        ValueUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ValueUser.setText("15");

        jPanel9.setBackground(new java.awt.Color(240, 0, 0));
        jPanel9.setPreferredSize(new java.awt.Dimension(146, 3));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 158, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        Labeltahunuser.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        Labeltahunuser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Labeltahunuser.setText("2023");

        javax.swing.GroupLayout PanelTotalUserLayout = new javax.swing.GroupLayout(PanelTotalUser);
        PanelTotalUser.setLayout(PanelTotalUserLayout);
        PanelTotalUserLayout.setHorizontalGroup(
            PanelTotalUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTotalUserLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12))
            .addGroup(PanelTotalUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelTotalUserLayout.createSequentialGroup()
                    .addGroup(PanelTotalUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LabelUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Labeltahunuser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelTotalUserLayout.createSequentialGroup()
                            .addGroup(PanelTotalUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ValueUser, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addGap(218, 218, 218)))
        );
        PanelTotalUserLayout.setVerticalGroup(
            PanelTotalUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12)
            .addGroup(PanelTotalUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelTotalUserLayout.createSequentialGroup()
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(60, 60, 60)
                    .addComponent(LabelUser, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Labeltahunuser)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                    .addComponent(ValueUser, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(34, 34, 34)))
        );

        PanelTotalPemain.setBackground(new java.awt.Color(255, 251, 251));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Dashboard/ImagePemain.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });

        LabelPlayer.setFont(new java.awt.Font("Verdana", 1, 25)); // NOI18N
        LabelPlayer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelPlayer.setText("PLAYER");

        ValuePlayer.setBackground(new java.awt.Color(240, 0, 0));
        ValuePlayer.setFont(new java.awt.Font("Verdana", 1, 70)); // NOI18N
        ValuePlayer.setForeground(new java.awt.Color(240, 0, 0));
        ValuePlayer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ValuePlayer.setText("15");

        jPanel5.setBackground(new java.awt.Color(240, 0, 0));
        jPanel5.setPreferredSize(new java.awt.Dimension(146, 3));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 146, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        Labelyear.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        Labelyear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Labelyear.setText("2023");

        javax.swing.GroupLayout PanelTotalPemainLayout = new javax.swing.GroupLayout(PanelTotalPemain);
        PanelTotalPemain.setLayout(PanelTotalPemainLayout);
        PanelTotalPemainLayout.setHorizontalGroup(
            PanelTotalPemainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTotalPemainLayout.createSequentialGroup()
                .addGroup(PanelTotalPemainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTotalPemainLayout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(ValuePlayer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Labelyear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelPlayer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7))
        );
        PanelTotalPemainLayout.setVerticalGroup(
            PanelTotalPemainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelTotalPemainLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(LabelPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Labelyear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ValuePlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        PanelTotalBerita.setBackground(new java.awt.Color(255, 255, 255));

        LabelBerita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Dashboard/ImagePemain.png"))); // NOI18N
        LabelBerita.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                LabelBeritaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                LabelBeritaFocusLost(evt);
            }
        });
        LabelBerita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LabelBeritaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabelBeritaMouseExited(evt);
            }
        });

        LabelText.setFont(new java.awt.Font("Verdana", 1, 25)); // NOI18N
        LabelText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelText.setText("PLAYER");

        LabelTotal.setBackground(new java.awt.Color(240, 0, 0));
        LabelTotal.setFont(new java.awt.Font("Verdana", 1, 70)); // NOI18N
        LabelTotal.setForeground(new java.awt.Color(240, 0, 0));
        LabelTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTotal.setText("15");

        PanelLine.setBackground(new java.awt.Color(240, 0, 0));
        PanelLine.setPreferredSize(new java.awt.Dimension(146, 3));

        javax.swing.GroupLayout PanelLineLayout = new javax.swing.GroupLayout(PanelLine);
        PanelLine.setLayout(PanelLineLayout);
        PanelLineLayout.setHorizontalGroup(
            PanelLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 146, Short.MAX_VALUE)
        );
        PanelLineLayout.setVerticalGroup(
            PanelLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        LabelTahun.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        LabelTahun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTahun.setText("2023");

        javax.swing.GroupLayout PanelTotalBeritaLayout = new javax.swing.GroupLayout(PanelTotalBerita);
        PanelTotalBerita.setLayout(PanelTotalBeritaLayout);
        PanelTotalBeritaLayout.setHorizontalGroup(
            PanelTotalBeritaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTotalBeritaLayout.createSequentialGroup()
                .addGroup(PanelTotalBeritaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTotalBeritaLayout.createSequentialGroup()
                        .addComponent(PanelLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(LabelTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelTahun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelBerita))
        );
        PanelTotalBeritaLayout.setVerticalGroup(
            PanelTotalBeritaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelBerita, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
            .addGroup(PanelTotalBeritaLayout.createSequentialGroup()
                .addComponent(PanelLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(LabelText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelTahun)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout PaneltotalLayout = new javax.swing.GroupLayout(Paneltotal);
        Paneltotal.setLayout(PaneltotalLayout);
        PaneltotalLayout.setHorizontalGroup(
            PaneltotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaneltotalLayout.createSequentialGroup()
                .addComponent(PanelTotalUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelTotalPemain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(PanelTotalBerita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PaneltotalLayout.setVerticalGroup(
            PaneltotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaneltotalLayout.createSequentialGroup()
                .addGroup(PaneltotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelTotalBerita, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelTotalUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelTotalPemain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        PanelTable.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel6.setText("User Recents");

        Tabledata.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Tabledata.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Tabledata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        Tabledata.setGridColor(new java.awt.Color(204, 204, 204));
        Tabledata.setRowHeight(40);
        Tabledata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabledataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabledata);

        javax.swing.GroupLayout PanelTableLayout = new javax.swing.GroupLayout(PanelTable);
        PanelTable.setLayout(PanelTableLayout);
        PanelTableLayout.setHorizontalGroup(
            PanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(PanelTableLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelTableLayout.setVerticalGroup(
            PanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTableLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout PanelDashboardLayout = new javax.swing.GroupLayout(PanelDashboard);
        PanelDashboard.setLayout(PanelDashboardLayout);
        PanelDashboardLayout.setHorizontalGroup(
            PanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Paneltotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelDashboardLayout.setVerticalGroup(
            PanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDashboardLayout.createSequentialGroup()
                .addComponent(PanelImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Paneltotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MainPanel.add(PanelDashboard, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout ContainerPanelLayout = new javax.swing.GroupLayout(ContainerPanel);
        ContainerPanel.setLayout(ContainerPanelLayout);
        ContainerPanelLayout.setHorizontalGroup(
            ContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ContainerPanelLayout.createSequentialGroup()
                .addComponent(SidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ContainerPanelLayout.setVerticalGroup(
            ContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerPanelLayout.createSequentialGroup()
                .addComponent(HeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SidebarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContainerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(ContainerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btndashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndashboardMouseEntered
        // TODO add your handling code here:
        PanelButton.setBackground(new Color(240, 0, 0));
        btndashboard.setForeground(Color.white);
    }//GEN-LAST:event_btndashboardMouseEntered

    private void btndashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndashboardMouseExited
        // TODO add your handling code here:
        PanelButton.setBackground(new Color(255, 255, 255));
        btndashboard.setForeground(Color.black);
    }//GEN-LAST:event_btndashboardMouseExited

    private void btndashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndashboardMouseClicked
        // TODO add your handling code here:
        MainPanel.removeAll();

        MainPanel.add(PanelDashboard);
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_btndashboardMouseClicked

    private void TabledataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabledataMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TabledataMouseClicked

    private void LabelBeritaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LabelBeritaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_LabelBeritaFocusGained

    private void LabelBeritaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LabelBeritaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_LabelBeritaFocusLost

    private void LabelBeritaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelBeritaMouseEntered
        // TODO add your handling code here:
        PanelTotalBerita.setBackground(new Color(240,0,0));
        LabelTotal.setForeground(Color.white);
        LabelText.setForeground(Color.white);
        LabelTahun.setForeground(Color.white);
    }//GEN-LAST:event_LabelBeritaMouseEntered

    private void LabelBeritaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelBeritaMouseExited
        // TODO add your handling code here:
        PanelTotalBerita.setBackground(new Color(255,255,255));
        PanelLine.setBackground(new Color(240,0,0));
        LabelTotal.setForeground(new Color(240,0,0));
        LabelText.setForeground(Color.black);
        LabelTahun.setForeground(Color.black);
    }//GEN-LAST:event_LabelBeritaMouseExited

    private void btnuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnuserMouseClicked
        // TODO add your handling code here:
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();
        
        UserPage panelUser = new UserPage();
        MainPanel.add(panelUser);
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_btnuserMouseClicked

    private void btnuserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnuserMouseEntered
        // TODO add your handling code here:
        PanelBtnUser.setBackground(new Color(240, 0, 0));
        btnuser.setForeground(Color.white);
    }//GEN-LAST:event_btnuserMouseEntered

    private void btnuserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnuserMouseExited
        // TODO add your handling code here:
        PanelBtnUser.setBackground(new Color(255, 255, 255));
        btnuser.setForeground(Color.black);
    }//GEN-LAST:event_btnuserMouseExited

    private void btnplayerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnplayerMouseClicked
        // TODO add your handling code here:
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();
        
        PlayerPage panelPlayer = new PlayerPage();
        MainPanel.add(panelPlayer);
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_btnplayerMouseClicked

    private void btnplayerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnplayerMouseEntered
        // TODO add your handling code here:
        PanelBtnPlayer.setBackground(new Color(240, 0, 0));
        btnplayer.setForeground(Color.white);
    }//GEN-LAST:event_btnplayerMouseEntered

    private void btnplayerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnplayerMouseExited
        // TODO add your handling code here:
        PanelBtnPlayer.setBackground(new Color(255, 255, 255));
        btnplayer.setForeground(Color.black);
    }//GEN-LAST:event_btnplayerMouseExited

    private void btnstatistikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnstatistikMouseClicked
        // TODO add your handling code here:
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();
        
        StatistikPlayerPage panelStatistik = new StatistikPlayerPage();
        MainPanel.add(panelStatistik);
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_btnstatistikMouseClicked

    private void btnstatistikMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnstatistikMouseEntered
        // TODO add your handling code here:
        PanelBtnStatistik.setBackground(new Color(240, 0, 0));
        btnstatistik.setForeground(Color.white);
    }//GEN-LAST:event_btnstatistikMouseEntered

    private void btnstatistikMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnstatistikMouseExited
        // TODO add your handling code here:
        PanelBtnStatistik.setBackground(new Color(255, 255, 255));
        btnstatistik.setForeground(Color.black);
    }//GEN-LAST:event_btnstatistikMouseExited

    private void btnnewsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnnewsMouseClicked
        // TODO add your handling code here:
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();
        
        NewsPage panelNews = new NewsPage();
        MainPanel.add(panelNews);
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_btnnewsMouseClicked

    private void btnnewsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnnewsMouseEntered
        // TODO add your handling code here:
        PanelBtnNews.setBackground(new Color(240, 0, 0));
        btnnews.setForeground(Color.white);
    }//GEN-LAST:event_btnnewsMouseEntered

    private void btnnewsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnnewsMouseExited
        // TODO add your handling code here:
        PanelBtnNews.setBackground(new Color(255, 255, 255));
        btnnews.setForeground(Color.black);
    }//GEN-LAST:event_btnnewsMouseExited

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        // TODO add your handling code here:
        PanelTotalPemain.setBackground(new Color(240,0,0));
        ValuePlayer.setForeground(Color.white);
        LabelPlayer.setForeground(Color.white);
        Labelyear.setForeground(Color.white);
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        // TODO add your handling code here:
        PanelTotalPemain.setBackground(new Color(255,255,255));
        PanelLine.setBackground(new Color(240,0,0));
        ValuePlayer.setForeground(new Color(240,0,0));
        LabelPlayer.setForeground(Color.black);
        Labelyear.setForeground(Color.black);
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
        // TODO add your handling code here:
        PanelTotalUser.setBackground(new Color(240,0,0));
        ValueUser.setForeground(Color.white);
        LabelUser.setForeground(Color.white);
        Labeltahunuser.setForeground(Color.white);
    }//GEN-LAST:event_jLabel12MouseEntered

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited
        // TODO add your handling code here:
        PanelTotalUser.setBackground(new Color(255,255,255));
        PanelLine.setBackground(new Color(240,0,0));
        ValueUser.setForeground(new Color(240,0,0));
        LabelUser.setForeground(Color.black);
        Labeltahunuser.setForeground(Color.black);
    }//GEN-LAST:event_jLabel12MouseExited

    private void btnlogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseExited
        // TODO add your handling code here:
        PanelLogout.setBackground(new Color(240, 0, 0));
        btnlogout.setForeground(Color.white);
    }//GEN-LAST:event_btnlogoutMouseExited

    private void btnlogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseEntered
        // TODO add your handling code here:
        PanelLogout.setBackground(new Color(127, 4, 4));
        btnlogout.setForeground(Color.white);
    }//GEN-LAST:event_btnlogoutMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContainerPanel;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JLabel LabelBerita;
    private javax.swing.JLabel LabelDatetime;
    private javax.swing.JLabel LabelPlayer;
    private javax.swing.JLabel LabelTahun;
    private javax.swing.JLabel LabelText;
    private javax.swing.JLabel LabelTotal;
    private javax.swing.JLabel LabelUser;
    private javax.swing.JLabel Labeltahunuser;
    private javax.swing.JLabel Labelyear;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel PanelBtnNews;
    private javax.swing.JPanel PanelBtnPlayer;
    private javax.swing.JPanel PanelBtnStatistik;
    private javax.swing.JPanel PanelBtnUser;
    private javax.swing.JPanel PanelButton;
    private javax.swing.JPanel PanelButton1;
    private javax.swing.JPanel PanelDashboard;
    private javax.swing.JPanel PanelImage;
    private javax.swing.JPanel PanelLine;
    private javax.swing.JPanel PanelLogout;
    private javax.swing.JPanel PanelTable;
    private javax.swing.JPanel PanelTotalBerita;
    private javax.swing.JPanel PanelTotalPemain;
    private javax.swing.JPanel PanelTotalUser;
    private javax.swing.JPanel Paneltotal;
    private javax.swing.JPanel SidebarPanel;
    private javax.swing.JTable Tabledata;
    private javax.swing.JLabel ValuePlayer;
    private javax.swing.JLabel ValueUser;
    private javax.swing.JLabel btndashboard;
    private javax.swing.JLabel btndashboard1;
    private javax.swing.JLabel btnlogout;
    private javax.swing.JLabel btnnews;
    private javax.swing.JLabel btnplayer;
    private javax.swing.JLabel btnstatistik;
    private javax.swing.JLabel btnuser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
